swirl()
sapply(flags, unique)
vapply(flags, unique, numeric(1))
ok()
sapply(flags, class)
vapply(flags, class, character(1))
?tapply
table(flags$landmass)
table(flags$animate)
tapply(flags$animate, flags$landmass, mean)
tapply(flags$population, flags$red, summary)
summary(landmasses)
tapply(summary)
tapply( flags$population, flags$landmass, summary)
savehistory("C:/Users/shipra.gupta/Desktop/datasciencecoursera/vapply_tapply_shipra.R")
