swirl()
2
swirl()
getwd()
ls()
x <- 9
ls()
list.files()
?list.files
args(list.files)
old.dir <- getwd()
dir.create("test.dir")
dir.create("testdir")
setwd(testdir)
setwd("testdir")
file.create("mytest.R")
list.files()
file.exsists("myrtest.r")
file.exsists("mytest.r")
file.exists("mytest.r")
file.info("mytest.R")
file.exists("mytest.R")
file.info()
file.info(mytest.R)
file.info("mytest.R")
file.rename("mytest.R", "mytest2.R")
file.copy("mytest2.R", "mytest3.R")
file.path("mytest3.R")
file.path("folder1", "folder2")
?dir.create
dir.create(file.path("testdir2", "testdir3"), recursive = TRUE)
unlink("testdir2", recursive = TRUE)
setwd(old.dir)
unlink("testdir2", recursive = TRUE)
unlink("testdir", recursive = TRUE)
savehistory("~/DATA_SCIENCE/workspace_files.R")
savehistory("~/DATA_SCIENCE/workspace_files.R")
